FROM europe-north1-docker.pkg.dev/cgr-nav/pull-through/nav.no/jre:openjdk-25@sha256:f8a52938231d3c891c16be58b44560b59395be496721c46fc512e454f3d6ce1e

ENV LANG='nb_NO.UTF-8' LANGUAGE='nb_NO:nb' LC_ALL='nb_NO.UTF-8' TZ="Europe/Oslo"

COPY build/libs/mediator-all.jar /app.jar

ENTRYPOINT ["java", "-jar", "/app.jar"]
